import 'css.gg/icons/scss/menu-left-alt.scss'
import 'css.gg/icons/scss/menu-right-alt.scss'
import 'css.gg/icons/scss/menu.scss'
import 'css.gg/icons/scss/math-minus.scss'
import 'css.gg/icons/scss/math-plus.scss'
import 'css.gg/icons/scss/close.scss'
